// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PaymentService
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class PaymentUpdated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"PaymentUpdated\",\"namespace\":\"PaymentService\",\"fields\":[{" +
				"\"name\":\"Id\",\"type\":\"long\"},{\"name\":\"OrderId\",\"type\":\"long\"},{\"name\":\"Price\",\"typ" +
				"e\":\"bytes\"},{\"name\":\"Status\",\"type\":\"boolean\"},{\"name\":\"DateCreate\",\"type\":\"long" +
				"\"}]}");
		private long _Id;
		private long _OrderId;
		private byte[] _Price;
		private bool _Status;
		private long _DateCreate;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return PaymentUpdated._SCHEMA;
			}
		}
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public long OrderId
		{
			get
			{
				return this._OrderId;
			}
			set
			{
				this._OrderId = value;
			}
		}
		public byte[] Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				this._Price = value;
			}
		}
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				this._Status = value;
			}
		}
		public long DateCreate
		{
			get
			{
				return this._DateCreate;
			}
			set
			{
				this._DateCreate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.OrderId;
			case 2: return this.Price;
			case 3: return this.Status;
			case 4: return this.DateCreate;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Int64)fieldValue; break;
			case 1: this.OrderId = (System.Int64)fieldValue; break;
			case 2: this.Price = (System.Byte[])fieldValue; break;
			case 3: this.Status = (System.Boolean)fieldValue; break;
			case 4: this.DateCreate = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
