// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NotificationService.WebApi.Common.AvroSchemas
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class OrderCreated : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""OrderCreated"",""namespace"":""OrderService"",""fields"":[{""name"":""Id"",""type"":""long""},{""name"":""ProductId"",""type"":""long""},{""name"":""Amount"",""type"":""int""},{""name"":""EmailClient"",""type"":""string""},{""name"":""Price"",""type"":""bytes""},{""name"":""PhoneNumber"",""type"":""string""}]}");
		private long _Id;
		private long _ProductId;
		private int _Amount;
		private string _EmailClient;
		private byte[] _Price;
		private string _PhoneNumber;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return OrderCreated._SCHEMA;
			}
		}
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public long ProductId
		{
			get
			{
				return this._ProductId;
			}
			set
			{
				this._ProductId = value;
			}
		}
		public int Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				this._Amount = value;
			}
		}
		public string EmailClient
		{
			get
			{
				return this._EmailClient;
			}
			set
			{
				this._EmailClient = value;
			}
		}
		public byte[] Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				this._Price = value;
			}
		}
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				this._PhoneNumber = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.ProductId;
			case 2: return this.Amount;
			case 3: return this.EmailClient;
			case 4: return this.Price;
			case 5: return this.PhoneNumber;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Int64)fieldValue; break;
			case 1: this.ProductId = (System.Int64)fieldValue; break;
			case 2: this.Amount = (System.Int32)fieldValue; break;
			case 3: this.EmailClient = (System.String)fieldValue; break;
			case 4: this.Price = (System.Byte[])fieldValue; break;
			case 5: this.PhoneNumber = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
